///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace WebPageTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The BBCWebTest recording.
    /// </summary>
    [TestModule("e946e514-7bb4-46b5-9bda-0d64b8cbe502", ModuleType.Recording, 1)]
    public partial class BBCWebTest : ITestModule
    {
        /// <summary>
        /// Holds an instance of the WebPageTestRepository repository.
        /// </summary>
        public static WebPageTestRepository repo = WebPageTestRepository.Instance;

        static BBCWebTest instance = new BBCWebTest();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public BBCWebTest()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static BBCWebTest Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Delay", "Waiting for 15s.", new RecordItemIndex(0));
            Delay.Duration(15000, false);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Homepage') on item 'BBCHome.Homepage'.", repo.BBCHome.HomepageInfo, new RecordItemIndex(1));
            //Validate.Attribute(repo.BBCHome.HomepageInfo, "InnerText", "Homepage");
            //Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Href='https://www.bbc.co.uk/') on item 'BBCHome.Homepage'.", repo.BBCHome.HomepageInfo, new RecordItemIndex(2));
            //Validate.Attribute(repo.BBCHome.HomepageInfo, "Href", "https://www.bbc.co.uk/");
            //Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=105,Height=30}) on item 'BBCHome.Homepage'.", repo.BBCHome.HomepageInfo, new RecordItemIndex(3));
            //Validate.ContainsImage(repo.BBCHome.HomepageInfo, Homepage_Screenshot1, Homepage_Screenshot1_Options);
            //Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Welcome to the BBC') on item 'BBCHome.WelcomeToTheBBC'.", repo.BBCHome.WelcomeToTheBBCInfo, new RecordItemIndex(4));
            Validate.Attribute(repo.BBCHome.WelcomeToTheBBCInfo, "InnerText", "Welcome to the BBC");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagName='h2') on item 'BBCHome.WelcomeToTheBBC'.", repo.BBCHome.WelcomeToTheBBCInfo, new RecordItemIndex(5));
            Validate.Attribute(repo.BBCHome.WelcomeToTheBBCInfo, "TagName", "h2");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'BBCHome.More' at 112;29.", repo.BBCHome.MoreInfo, new RecordItemIndex(6));
            repo.BBCHome.More.Click("112;29");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='More') on item 'BBCHome.OrbPanelMoreTitle'.", repo.BBCHome.OrbPanelMoreTitleInfo, new RecordItemIndex(7));
            Validate.Attribute(repo.BBCHome.OrbPanelMoreTitleInfo, "InnerText", "More");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagName='h2') on item 'BBCHome.OrbPanelMoreTitle'.", repo.BBCHome.OrbPanelMoreTitleInfo, new RecordItemIndex(8));
            Validate.Attribute(repo.BBCHome.OrbPanelMoreTitleInfo, "TagName", "h2");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=102,Height=41}) on item 'BBCHome.OrbPanelMoreTitle'.", repo.BBCHome.OrbPanelMoreTitleInfo, new RecordItemIndex(9));
            Validate.ContainsImage(repo.BBCHome.OrbPanelMoreTitleInfo, OrbPanelMoreTitle_Screenshot1, OrbPanelMoreTitle_Screenshot1_Options);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'BBCHome.Food' at 30;21.", repo.BBCHome.FoodInfo, new RecordItemIndex(10));
            repo.BBCHome.Food.Click("30;21");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Food') on item 'BBCHome.FoodHomepage'.", repo.BBCHome.FoodHomepageInfo, new RecordItemIndex(11));
            Validate.Attribute(repo.BBCHome.FoodHomepageInfo, "InnerText", "Food");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Href='https://www.bbc.co.uk/food') on item 'BBCHome.FoodHomepage'.", repo.BBCHome.FoodHomepageInfo, new RecordItemIndex(12));
            Validate.Attribute(repo.BBCHome.FoodHomepageInfo, "Href", "https://www.bbc.co.uk/food");
            Delay.Milliseconds(100);
            
            Report.Screenshot(ReportLevel.Info, "User", "", null, false, new RecordItemIndex(13));
            
        }

#region Image Feature Data
        CompressedImage Homepage_Screenshot1
        { get { return repo.BBCHome.HomepageInfo.GetScreenshot1(new Rectangle(0, 0, 105, 30)); } }

        Imaging.FindOptions Homepage_Screenshot1_Options
        { get { return Imaging.FindOptions.Default; } }

        CompressedImage OrbPanelMoreTitle_Screenshot1
        { get { return repo.BBCHome.OrbPanelMoreTitleInfo.GetScreenshot1(new Rectangle(0, 0, 102, 41)); } }

        Imaging.FindOptions OrbPanelMoreTitle_Screenshot1_Options
        { get { return Imaging.FindOptions.Default; } }

#endregion
    }
#pragma warning restore 0436
}
