///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace WebPageTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The OpenBrowser recording.
    /// </summary>
    [TestModule("00b44ec5-ec13-47b0-ab53-fa172ccf5e55", ModuleType.Recording, 1)]
    public partial class OpenBrowser : ITestModule
    {
        /// <summary>
        /// Holds an instance of the WebPageTestRepository repository.
        /// </summary>
        public static WebPageTestRepository repo = WebPageTestRepository.Instance;

        static OpenBrowser instance = new OpenBrowser();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public OpenBrowser()
        {
            webpageurl = "";
            browsername = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static OpenBrowser Instance
        {
            get { return instance; }
        }

#region Variables

        string _webpageurl;

        /// <summary>
        /// Gets or sets the value of variable webpageurl.
        /// </summary>
        [TestVariable("1ccc0aa4-a783-4990-9594-d1aa4736f69b")]
        public string webpageurl
        {
            get { return _webpageurl; }
            set { _webpageurl = value; }
        }

        string _browsername;

        /// <summary>
        /// Gets or sets the value of variable browsername.
        /// </summary>
        [TestVariable("5e1adcb2-82d2-4451-a3d2-826cd0c7e2bc")]
        public string browsername
        {
            get { return _browsername; }
            set { _browsername = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site URL in variable $webpageurl with browser specified by variable $browsername in maximized mode.", new RecordItemIndex(0));
            Host.Local.OpenBrowser(webpageurl, browsername, "", false, true, false, false, false);
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Website", "Opening web site 'https://www.virginmedia.com/' with browser 'IE' in normal mode.", new RecordItemIndex(1));
            //Host.Local.OpenBrowser("https://www.virginmedia.com/", "IE", "", false, false, false, false, false);
            //Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
