///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace WebPageTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The VMWebTest recording.
    /// </summary>
    [TestModule("2658fb00-181a-446c-99a6-2b4190a53350", ModuleType.Recording, 1)]
    public partial class VMWebTest : ITestModule
    {
        /// <summary>
        /// Holds an instance of the WebPageTestRepository repository.
        /// </summary>
        public static WebPageTestRepository repo = WebPageTestRepository.Instance;

        static VMWebTest instance = new VMWebTest();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public VMWebTest()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static VMWebTest Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            //Report.Log(ReportLevel.Info, "Website", "Opening web site 'https://www.virginmedia.com/' with browser 'IE' in normal mode.", new RecordItemIndex(0));
            //Host.Local.OpenBrowser("https://www.virginmedia.com/", "IE", "", false, false, false, false, false);
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VirginMediaOfficialSite.ConsentPromptSubmit' at 184;13.", repo.VirginMediaOfficialSite.ConsentPromptSubmitInfo, new RecordItemIndex(1));
            //repo.VirginMediaOfficialSite.ConsentPromptSubmit.Click("184;13");
            //Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 15s.", new RecordItemIndex(2));
            Delay.Duration(15000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Src='https://www.virginmedia.com/etc/designs/onecms/clientlibs/onecms-critical/img/header-vm-logo.lg.png') on item 'VirginMediaOfficialSite.VirginMedia'.", repo.VirginMediaOfficialSite.VirginMediaInfo, new RecordItemIndex(3));
            Validate.Attribute(repo.VirginMediaOfficialSite.VirginMediaInfo, "Src", "https://www.virginmedia.com/etc/designs/onecms/clientlibs/onecms-critical/img/header-vm-logo.lg.png");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=133,Height=82}) on item 'VirginMediaOfficialSite.VirginMedia'.", repo.VirginMediaOfficialSite.VirginMediaInfo, new RecordItemIndex(4));
            Validate.ContainsImage(repo.VirginMediaOfficialSite.VirginMediaInfo, VirginMedia_Screenshot1, VirginMedia_Screenshot1_Options);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='My Virgin Media\n    ') on item 'VirginMediaOfficialSite.MyVirginMedia'.", repo.VirginMediaOfficialSite.MyVirginMediaInfo, new RecordItemIndex(5));
            Validate.Attribute(repo.VirginMediaOfficialSite.MyVirginMediaInfo, "InnerText", "My Virgin Media\n    ");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Href='https://my.virginmedia.com/') on item 'VirginMediaOfficialSite.MyVirginMedia'.", repo.VirginMediaOfficialSite.MyVirginMediaInfo, new RecordItemIndex(6));
            Validate.Attribute(repo.VirginMediaOfficialSite.MyVirginMediaInfo, "Href", "https://my.virginmedia.com/");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VirginMediaOfficialSite.MyVirginMedia' at 83;6.", repo.VirginMediaOfficialSite.MyVirginMediaInfo, new RecordItemIndex(7));
            repo.VirginMediaOfficialSite.MyVirginMedia.Click("83;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VirginMediaMyVirginMedia.ATagVirginMedia' at 55;43.", repo.VirginMediaMyVirginMedia.ATagVirginMediaInfo, new RecordItemIndex(8));
            repo.VirginMediaMyVirginMedia.ATagVirginMedia.Click("55;43");
            Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VirginMediaOfficialSiteInternet.ClientCaption' at 1890;31.", repo.VirginMediaOfficialSiteInternet.ClientCaptionInfo, new RecordItemIndex(9));
            //repo.VirginMediaOfficialSiteInternet.ClientCaption.Click("1890;31");
            //Delay.Milliseconds(200);
            
        }

#region Image Feature Data
        CompressedImage VirginMedia_Screenshot1
        { get { return repo.VirginMediaOfficialSite.VirginMediaInfo.GetScreenshot1(new Rectangle(0, 0, 133, 82)); } }

        Imaging.FindOptions VirginMedia_Screenshot1_Options
        { get { return Imaging.FindOptions.Default; } }

#endregion
    }
#pragma warning restore 0436
}
