///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace WebPageTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the WebPageTestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
    [RepositoryFolder("44a44dba-0d21-424d-9680-11f589ae788d")]
    public partial class WebPageTestRepository : RepoGenBaseFolder
    {
        static WebPageTestRepository instance = new WebPageTestRepository();
        WebPageTestRepositoryFolders.BBCHomeAppFolder _bbchome;
        WebPageTestRepositoryFolders.BBCFoodRecipesAndInspirationFromAppFolder _bbcfoodrecipesandinspirationfrom;
        WebPageTestRepositoryFolders.BBCHomeInternetExplorerAppFolder _bbchomeinternetexplorer;
        WebPageTestRepositoryFolders.VirginMediaOfficialSiteAppFolder _virginmediaofficialsite;
        WebPageTestRepositoryFolders.VirginMediaMyVirginMediaAppFolder _virginmediamyvirginmedia;
        WebPageTestRepositoryFolders.VirginMediaOfficialSiteInternetAppFolder _virginmediaofficialsiteinternet;

        /// <summary>
        /// Gets the singleton class instance representing the WebPageTestRepository element repository.
        /// </summary>
        [RepositoryFolder("44a44dba-0d21-424d-9680-11f589ae788d")]
        public static WebPageTestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public WebPageTestRepository() 
            : base("WebPageTestRepository", "/", null, 0, false, "44a44dba-0d21-424d-9680-11f589ae788d", ".\\RepositoryImages\\WebPageTestRepository44a44dba.rximgres")
        {
            _bbchome = new WebPageTestRepositoryFolders.BBCHomeAppFolder(this);
            _bbcfoodrecipesandinspirationfrom = new WebPageTestRepositoryFolders.BBCFoodRecipesAndInspirationFromAppFolder(this);
            _bbchomeinternetexplorer = new WebPageTestRepositoryFolders.BBCHomeInternetExplorerAppFolder(this);
            _virginmediaofficialsite = new WebPageTestRepositoryFolders.VirginMediaOfficialSiteAppFolder(this);
            _virginmediamyvirginmedia = new WebPageTestRepositoryFolders.VirginMediaMyVirginMediaAppFolder(this);
            _virginmediaofficialsiteinternet = new WebPageTestRepositoryFolders.VirginMediaOfficialSiteInternetAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("44a44dba-0d21-424d-9680-11f589ae788d")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The BBCHome folder.
        /// </summary>
        [RepositoryFolder("515c24d7-486d-4277-a601-c02eb642507d")]
        public virtual WebPageTestRepositoryFolders.BBCHomeAppFolder BBCHome
        {
            get { return _bbchome; }
        }

        /// <summary>
        /// The BBCFoodRecipesAndInspirationFrom folder.
        /// </summary>
        [RepositoryFolder("bea5241c-f54c-4083-b88a-a74c65da4c9e")]
        public virtual WebPageTestRepositoryFolders.BBCFoodRecipesAndInspirationFromAppFolder BBCFoodRecipesAndInspirationFrom
        {
            get { return _bbcfoodrecipesandinspirationfrom; }
        }

        /// <summary>
        /// The BBCHomeInternetExplorer folder.
        /// </summary>
        [RepositoryFolder("a21a7dd7-f98d-49f8-9115-d00edc2b3179")]
        public virtual WebPageTestRepositoryFolders.BBCHomeInternetExplorerAppFolder BBCHomeInternetExplorer
        {
            get { return _bbchomeinternetexplorer; }
        }

        /// <summary>
        /// The VirginMediaOfficialSite folder.
        /// </summary>
        [RepositoryFolder("0bc1a895-3a19-4ef8-b490-ad6d584490b7")]
        public virtual WebPageTestRepositoryFolders.VirginMediaOfficialSiteAppFolder VirginMediaOfficialSite
        {
            get { return _virginmediaofficialsite; }
        }

        /// <summary>
        /// The VirginMediaMyVirginMedia folder.
        /// </summary>
        [RepositoryFolder("b5654430-099b-438a-a9e1-096923495055")]
        public virtual WebPageTestRepositoryFolders.VirginMediaMyVirginMediaAppFolder VirginMediaMyVirginMedia
        {
            get { return _virginmediamyvirginmedia; }
        }

        /// <summary>
        /// The VirginMediaOfficialSiteInternet folder.
        /// </summary>
        [RepositoryFolder("4f074a5d-b299-418e-aa74-581c78a1e9ea")]
        public virtual WebPageTestRepositoryFolders.VirginMediaOfficialSiteInternetAppFolder VirginMediaOfficialSiteInternet
        {
            get { return _virginmediaofficialsiteinternet; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
    public partial class WebPageTestRepositoryFolders
    {
        /// <summary>
        /// The BBCHomeAppFolder folder.
        /// </summary>
        [RepositoryFolder("515c24d7-486d-4277-a601-c02eb642507d")]
        public partial class BBCHomeAppFolder : RepoGenBaseFolder
        {
            HomepageInfoClass _homepageInfo;
            RepoItemInfo _welcometothebbcInfo;
            RepoItemInfo _moreInfo;
            OrbPanelMoreTitleInfoClass _orbpanelmoretitleInfo;
            RepoItemInfo _foodInfo;
            RepoItemInfo _foodhomepageInfo;

            /// <summary>
            /// Creates a new BBCHome  folder.
            /// </summary>
            public BBCHomeAppFolder(RepoGenBaseFolder parentFolder) :
                    base("BBCHome", "/dom[@domain='www.bbc.co.uk']", parentFolder, 30000, null, false, "515c24d7-486d-4277-a601-c02eb642507d", "")
            {
                _homepageInfo = new HomepageInfoClass(this);
                _welcometothebbcInfo = new RepoItemInfo(this, "WelcomeToTheBBC", ".//div[#'orb-modules']/div[2]/section[1]/?/?/h2[@innertext='Welcome to the BBC']", 30000, null, "32e8816d-bb7e-40fb-be14-2f4ffc2e5819");
                _moreInfo = new RepoItemInfo(this, "More", ".//li[#'orb-nav-more']/a[@innertext='More']", 30000, null, "b5948d5f-e077-45c4-ba44-f94a836c4967");
                _orbpanelmoretitleInfo = new OrbPanelMoreTitleInfoClass(this);
                _foodInfo = new RepoItemInfo(this, "Food", ".//div[#'orb-panel-more']/?/?/ul/?/?/a[@innertext='Food']", 30000, null, "804793a7-f8a0-44ec-9281-7b52e44590a1");
                _foodhomepageInfo = new RepoItemInfo(this, "FoodHomepage", ".//div[#'main-content']/div[1]/div[1]/?/?/a[@innertext='Food']", 30000, null, "da77b69c-631e-4db9-bf27-7ff8d5a50670");
            }

            /// <summary>
            /// The HomepageInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("2e89688c-f72e-4057-af0b-26f80e1ba1b1")]
            public class HomepageInfoClass : RepoItemInfo
            {
                /// <summary>
                /// HomepageInfoClass class constructor.
                /// </summary>
                public HomepageInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "Homepage", ".//div[#'orb-header']//a[@innertext='Homepage']", 30000, null, "2e89688c-f72e-4057-af0b-26f80e1ba1b1")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("72a065de-7812-4c5a-9d99-b3b4082dabcf")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("72a065de-7812-4c5a-9d99-b3b4082dabcf");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("72a065de-7812-4c5a-9d99-b3b4082dabcf")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("72a065de-7812-4c5a-9d99-b3b4082dabcf", cropRect);
                }
            }

            /// <summary>
            /// The OrbPanelMoreTitleInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("ba9cff5b-5184-4ce8-a22e-cd1165b65e99")]
            public class OrbPanelMoreTitleInfoClass : RepoItemInfo
            {
                /// <summary>
                /// OrbPanelMoreTitleInfoClass class constructor.
                /// </summary>
                public OrbPanelMoreTitleInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "OrbPanelMoreTitle", ".//h2[#'orb-panel-more-title']", 30000, null, "ba9cff5b-5184-4ce8-a22e-cd1165b65e99")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("d2b38f80-de9d-4c96-8217-fa2fa4fed50a")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("d2b38f80-de9d-4c96-8217-fa2fa4fed50a");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("d2b38f80-de9d-4c96-8217-fa2fa4fed50a")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("d2b38f80-de9d-4c96-8217-fa2fa4fed50a", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("515c24d7-486d-4277-a601-c02eb642507d")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("515c24d7-486d-4277-a601-c02eb642507d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Homepage item.
            /// </summary>
            [RepositoryItem("2e89688c-f72e-4057-af0b-26f80e1ba1b1")]
            public virtual Ranorex.ATag Homepage
            {
                get
                {
                    return _homepageInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Homepage item info.
            /// </summary>
            [RepositoryItemInfo("2e89688c-f72e-4057-af0b-26f80e1ba1b1")]
            public virtual HomepageInfoClass HomepageInfo
            {
                get
                {
                    return _homepageInfo;
                }
            }

            /// <summary>
            /// The WelcomeToTheBBC item.
            /// </summary>
            [RepositoryItem("32e8816d-bb7e-40fb-be14-2f4ffc2e5819")]
            public virtual Ranorex.H2Tag WelcomeToTheBBC
            {
                get
                {
                    return _welcometothebbcInfo.CreateAdapter<Ranorex.H2Tag>(true);
                }
            }

            /// <summary>
            /// The WelcomeToTheBBC item info.
            /// </summary>
            [RepositoryItemInfo("32e8816d-bb7e-40fb-be14-2f4ffc2e5819")]
            public virtual RepoItemInfo WelcomeToTheBBCInfo
            {
                get
                {
                    return _welcometothebbcInfo;
                }
            }

            /// <summary>
            /// The More item.
            /// </summary>
            [RepositoryItem("b5948d5f-e077-45c4-ba44-f94a836c4967")]
            public virtual Ranorex.ATag More
            {
                get
                {
                    return _moreInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The More item info.
            /// </summary>
            [RepositoryItemInfo("b5948d5f-e077-45c4-ba44-f94a836c4967")]
            public virtual RepoItemInfo MoreInfo
            {
                get
                {
                    return _moreInfo;
                }
            }

            /// <summary>
            /// The OrbPanelMoreTitle item.
            /// </summary>
            [RepositoryItem("ba9cff5b-5184-4ce8-a22e-cd1165b65e99")]
            public virtual Ranorex.H2Tag OrbPanelMoreTitle
            {
                get
                {
                    return _orbpanelmoretitleInfo.CreateAdapter<Ranorex.H2Tag>(true);
                }
            }

            /// <summary>
            /// The OrbPanelMoreTitle item info.
            /// </summary>
            [RepositoryItemInfo("ba9cff5b-5184-4ce8-a22e-cd1165b65e99")]
            public virtual OrbPanelMoreTitleInfoClass OrbPanelMoreTitleInfo
            {
                get
                {
                    return _orbpanelmoretitleInfo;
                }
            }

            /// <summary>
            /// The Food item.
            /// </summary>
            [RepositoryItem("804793a7-f8a0-44ec-9281-7b52e44590a1")]
            public virtual Ranorex.ATag Food
            {
                get
                {
                    return _foodInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Food item info.
            /// </summary>
            [RepositoryItemInfo("804793a7-f8a0-44ec-9281-7b52e44590a1")]
            public virtual RepoItemInfo FoodInfo
            {
                get
                {
                    return _foodInfo;
                }
            }

            /// <summary>
            /// The FoodHomepage item.
            /// </summary>
            [RepositoryItem("da77b69c-631e-4db9-bf27-7ff8d5a50670")]
            public virtual Ranorex.ATag FoodHomepage
            {
                get
                {
                    return _foodhomepageInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The FoodHomepage item info.
            /// </summary>
            [RepositoryItemInfo("da77b69c-631e-4db9-bf27-7ff8d5a50670")]
            public virtual RepoItemInfo FoodHomepageInfo
            {
                get
                {
                    return _foodhomepageInfo;
                }
            }
        }

        /// <summary>
        /// The BBCFoodRecipesAndInspirationFromAppFolder folder.
        /// </summary>
        [RepositoryFolder("bea5241c-f54c-4083-b88a-a74c65da4c9e")]
        public partial class BBCFoodRecipesAndInspirationFromAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _closetabctrlpluswInfo;

            /// <summary>
            /// Creates a new BBCFoodRecipesAndInspirationFrom  folder.
            /// </summary>
            public BBCFoodRecipesAndInspirationFromAppFolder(RepoGenBaseFolder parentFolder) :
                    base("BBCFoodRecipesAndInspirationFrom", "/form[@title~'^BBC\\ Food\\ -\\ Recipes\\ and\\ in']", parentFolder, 30000, null, true, "bea5241c-f54c-4083-b88a-a74c65da4c9e", "")
            {
                _closetabctrlpluswInfo = new RepoItemInfo(this, "CloseTabCtrlPlusW", ".//container[@class='TabBandClass']/?/?/tabpagelist[@accessiblename='Tab Row']/tabpage[@accessiblename~'^BBC\\ Food\\ -\\ Recipes\\ and\\ in']/button[@accessiblename='Close Tab (Ctrl+W)']", 30000, null, "4776427b-6862-4dd1-9d3d-6125462fa87e");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("bea5241c-f54c-4083-b88a-a74c65da4c9e")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("bea5241c-f54c-4083-b88a-a74c65da4c9e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CloseTabCtrlPlusW item.
            /// </summary>
            [RepositoryItem("4776427b-6862-4dd1-9d3d-6125462fa87e")]
            public virtual Ranorex.Button CloseTabCtrlPlusW
            {
                get
                {
                    return _closetabctrlpluswInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The CloseTabCtrlPlusW item info.
            /// </summary>
            [RepositoryItemInfo("4776427b-6862-4dd1-9d3d-6125462fa87e")]
            public virtual RepoItemInfo CloseTabCtrlPlusWInfo
            {
                get
                {
                    return _closetabctrlpluswInfo;
                }
            }
        }

        /// <summary>
        /// The BBCHomeInternetExplorerAppFolder folder.
        /// </summary>
        [RepositoryFolder("a21a7dd7-f98d-49f8-9115-d00edc2b3179")]
        public partial class BBCHomeInternetExplorerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _clientcaptionInfo;

            /// <summary>
            /// Creates a new BBCHomeInternetExplorer  folder.
            /// </summary>
            public BBCHomeInternetExplorerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("BBCHomeInternetExplorer", "/form[@title~'^BBC\\ -\\ Home\\ -\\ Internet\\ Exp']", parentFolder, 30000, null, true, "a21a7dd7-f98d-49f8-9115-d00edc2b3179", "")
            {
                _clientcaptionInfo = new RepoItemInfo(this, "ClientCaption", "element[@class='Client Caption']", 30000, null, "6c4318d2-5b8c-4b17-9c58-eea8655f78b6");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a21a7dd7-f98d-49f8-9115-d00edc2b3179")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a21a7dd7-f98d-49f8-9115-d00edc2b3179")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ClientCaption item.
            /// </summary>
            [RepositoryItem("6c4318d2-5b8c-4b17-9c58-eea8655f78b6")]
            public virtual Ranorex.Unknown ClientCaption
            {
                get
                {
                    return _clientcaptionInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The ClientCaption item info.
            /// </summary>
            [RepositoryItemInfo("6c4318d2-5b8c-4b17-9c58-eea8655f78b6")]
            public virtual RepoItemInfo ClientCaptionInfo
            {
                get
                {
                    return _clientcaptionInfo;
                }
            }
        }

        /// <summary>
        /// The VirginMediaOfficialSiteAppFolder folder.
        /// </summary>
        [RepositoryFolder("0bc1a895-3a19-4ef8-b490-ad6d584490b7")]
        public partial class VirginMediaOfficialSiteAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _consentpromptsubmitInfo;
            VirginMediaInfoClass _virginmediaInfo;
            RepoItemInfo _myvirginmediaInfo;

            /// <summary>
            /// Creates a new VirginMediaOfficialSite  folder.
            /// </summary>
            public VirginMediaOfficialSiteAppFolder(RepoGenBaseFolder parentFolder) :
                    base("VirginMediaOfficialSite", "/dom[@domain='www.virginmedia.com']", parentFolder, 30000, null, false, "0bc1a895-3a19-4ef8-b490-ad6d584490b7", "")
            {
                _consentpromptsubmitInfo = new RepoItemInfo(this, "ConsentPromptSubmit", ".//a[#'consent_prompt_submit']", 30000, null, "0b2b06f7-0883-4b8f-92da-04ce523e792f");
                _virginmediaInfo = new VirginMediaInfoClass(this);
                _myvirginmediaInfo = new RepoItemInfo(this, "MyVirginMedia", ".//div[#'unified-header']/div/div/div[2]/div[1]/div[3]/ul/li[2]/a[@innertext='My Virgin Media    ']", 30000, null, "10a84036-b834-47ee-baaa-8eabdc10cf7f");
            }

            /// <summary>
            /// The VirginMediaInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("5fc735ee-588e-4f41-bfda-644bc60b6c75")]
            public class VirginMediaInfoClass : RepoItemInfo
            {
                /// <summary>
                /// VirginMediaInfoClass class constructor.
                /// </summary>
                public VirginMediaInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "VirginMedia", ".//div[#'unified-header']/div/div/div[1]/a[@href~'^https://www\\.virginmedia\\.c']/?/?/img[@alt='Virgin Media']", 30000, null, "5fc735ee-588e-4f41-bfda-644bc60b6c75")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("06972e43-9de8-4b3c-b04c-d890793bfc6d")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("06972e43-9de8-4b3c-b04c-d890793bfc6d");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("06972e43-9de8-4b3c-b04c-d890793bfc6d")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("06972e43-9de8-4b3c-b04c-d890793bfc6d", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("0bc1a895-3a19-4ef8-b490-ad6d584490b7")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("0bc1a895-3a19-4ef8-b490-ad6d584490b7")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ConsentPromptSubmit item.
            /// </summary>
            [RepositoryItem("0b2b06f7-0883-4b8f-92da-04ce523e792f")]
            public virtual Ranorex.ATag ConsentPromptSubmit
            {
                get
                {
                    return _consentpromptsubmitInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ConsentPromptSubmit item info.
            /// </summary>
            [RepositoryItemInfo("0b2b06f7-0883-4b8f-92da-04ce523e792f")]
            public virtual RepoItemInfo ConsentPromptSubmitInfo
            {
                get
                {
                    return _consentpromptsubmitInfo;
                }
            }

            /// <summary>
            /// The VirginMedia item.
            /// </summary>
            [RepositoryItem("5fc735ee-588e-4f41-bfda-644bc60b6c75")]
            public virtual Ranorex.ImgTag VirginMedia
            {
                get
                {
                    return _virginmediaInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The VirginMedia item info.
            /// </summary>
            [RepositoryItemInfo("5fc735ee-588e-4f41-bfda-644bc60b6c75")]
            public virtual VirginMediaInfoClass VirginMediaInfo
            {
                get
                {
                    return _virginmediaInfo;
                }
            }

            /// <summary>
            /// The MyVirginMedia item.
            /// </summary>
            [RepositoryItem("10a84036-b834-47ee-baaa-8eabdc10cf7f")]
            public virtual Ranorex.ATag MyVirginMedia
            {
                get
                {
                    return _myvirginmediaInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The MyVirginMedia item info.
            /// </summary>
            [RepositoryItemInfo("10a84036-b834-47ee-baaa-8eabdc10cf7f")]
            public virtual RepoItemInfo MyVirginMediaInfo
            {
                get
                {
                    return _myvirginmediaInfo;
                }
            }
        }

        /// <summary>
        /// The VirginMediaMyVirginMediaAppFolder folder.
        /// </summary>
        [RepositoryFolder("b5654430-099b-438a-a9e1-096923495055")]
        public partial class VirginMediaMyVirginMediaAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _atagvirginmediaInfo;

            /// <summary>
            /// Creates a new VirginMediaMyVirginMedia  folder.
            /// </summary>
            public VirginMediaMyVirginMediaAppFolder(RepoGenBaseFolder parentFolder) :
                    base("VirginMediaMyVirginMedia", "/dom[@domain='my.virginmedia.com']", parentFolder, 30000, null, false, "b5654430-099b-438a-a9e1-096923495055", "")
            {
                _atagvirginmediaInfo = new RepoItemInfo(this, "ATagVirginMedia", ".//h1[#'vm-logo']/a[@innertext~'^\\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ Virg']", 30000, null, "e6e03530-4f7b-4db4-87db-2f93a046c028");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b5654430-099b-438a-a9e1-096923495055")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b5654430-099b-438a-a9e1-096923495055")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ATagVirginMedia item.
            /// </summary>
            [RepositoryItem("e6e03530-4f7b-4db4-87db-2f93a046c028")]
            public virtual Ranorex.ATag ATagVirginMedia
            {
                get
                {
                    return _atagvirginmediaInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ATagVirginMedia item info.
            /// </summary>
            [RepositoryItemInfo("e6e03530-4f7b-4db4-87db-2f93a046c028")]
            public virtual RepoItemInfo ATagVirginMediaInfo
            {
                get
                {
                    return _atagvirginmediaInfo;
                }
            }
        }

        /// <summary>
        /// The VirginMediaOfficialSiteInternetAppFolder folder.
        /// </summary>
        [RepositoryFolder("4f074a5d-b299-418e-aa74-581c78a1e9ea")]
        public partial class VirginMediaOfficialSiteInternetAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _clientcaptionInfo;

            /// <summary>
            /// Creates a new VirginMediaOfficialSiteInternet  folder.
            /// </summary>
            public VirginMediaOfficialSiteInternetAppFolder(RepoGenBaseFolder parentFolder) :
                    base("VirginMediaOfficialSiteInternet", "/form[@title~'^Virgin\\ Media\\ -\\ Official\\ S']", parentFolder, 30000, null, true, "4f074a5d-b299-418e-aa74-581c78a1e9ea", "")
            {
                _clientcaptionInfo = new RepoItemInfo(this, "ClientCaption", "element[@class='Client Caption']", 30000, null, "2dab4340-f275-4e94-a303-48c81debeec3");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("4f074a5d-b299-418e-aa74-581c78a1e9ea")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("4f074a5d-b299-418e-aa74-581c78a1e9ea")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ClientCaption item.
            /// </summary>
            [RepositoryItem("2dab4340-f275-4e94-a303-48c81debeec3")]
            public virtual Ranorex.Unknown ClientCaption
            {
                get
                {
                    return _clientcaptionInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The ClientCaption item info.
            /// </summary>
            [RepositoryItemInfo("2dab4340-f275-4e94-a303-48c81debeec3")]
            public virtual RepoItemInfo ClientCaptionInfo
            {
                get
                {
                    return _clientcaptionInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}